name: Build release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo apt install yasm
      - run: ./build.sh
      - run: python3 .github/workflows/name_release.py
        id: name_release
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.name_release.outputs.release_name }}
          name: "Snapshot ${{ steps.name_release.outputs.release_name }}"
          files: miniforth.img
